Missing dependency added to requirements.txt
While executing the python emailOsint.py the following error occured:
ImportError: No module named cfscrape

Adding the missing module fixed it :)